# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BTTCoach' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BornToughTrainer
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'SDWebImage', '~> 4.0'
pod 'IQKeyboardManager'
pod 'CameraManager'
pod "Player", "~> 0.8.0"


pod 'JSQMessagesViewController'


end
